package net.exacode.spring.web.processor;

import java.io.IOException;
import java.io.OutputStream;
import java.io.PrintWriter;
import java.util.HashMap;
import java.util.Map;

import javax.annotation.processing.Filer;
import javax.annotation.processing.ProcessingEnvironment;
import javax.tools.Diagnostic.Kind;

import net.exacode.spring.web.processor.model.MetaController;
import freemarker.template.Configuration;
import freemarker.template.Template;
import freemarker.template.TemplateException;

/**
 * Responsible for writing meta model from context generated by
 * {@link MetaControllerGenerator}.
 * <p/>
 * This implementation uses FreeMarker library.
 * 
 * @author mendlik
 * 
 */
public class MetaCotrollerWriter {

	private final ProcessingEnvironment processingEnv;

	private final Configuration templateConfiguration;

	private static final String META_MODEL_TEMPLATE = "model.ftl";

	public MetaCotrollerWriter(ProcessingEnvironment processingEnv) {
		this.processingEnv = processingEnv;
		this.templateConfiguration = new Configuration();
		this.templateConfiguration.setClassForTemplateLoading(this.getClass(),
				"/");
	}

	public void write(MetaController mappedController) {
		String fileName = mappedController.getType().getCanonicalName();
		Map<String, Object> context = new HashMap<String, Object>();
		context.put("controller", mappedController);
		writeTemplate(context, META_MODEL_TEMPLATE, fileName);
	}

	private void writeTemplate(Map<String, Object> context,
			String templateFileName, String outputFileName) {
		Filer filer = processingEnv.getFiler();
		try {
			OutputStream os = filer.createSourceFile(outputFileName)
					.openOutputStream();
			PrintWriter pw = new PrintWriter(os);

			Template template = templateConfiguration
					.getTemplate(templateFileName);
			template.process(context, pw);

			pw.close();
			os.close();
		} catch (IOException | TemplateException e) {
			processingEnv.getMessager().printMessage(
					Kind.ERROR,
					"Could not create source file for " + outputFileName + ": "
							+ e);
		}
	}
}
